debug: true
server:
  port: 5000
spring:
  mvc:
    dispatch-options-request: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  profiles:
    active: "dev"
  #    active: "prod"
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 50MB
    ## default connection pool
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      ## PostgreSQL test
    #    url: jdbc:postgresql://localhost:5432/postgres
    #prod
    #    url: jdbc:postgresql://db-linkme-club.cgfbguuqliuk.eu-west-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    platform: all
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    properties:
  #      hibernate:
  #          format-sql: true
  session:
    store-type: jdbc
  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: linkmeclub@gmail.com
    #    password: Secret13
    #    password: P@ssw0rd13!
    password: jazhfxqgtpuponst
    protocol: smtp
    #    tls: true
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: DEBUG
params:
  hostUrl: linkme.club/
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE