spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://db-linkme-club.cgfbguuqliuk.eu-west-1.rds.amazonaws.com:5432/postgres
params:
  redirectUrl: http://linkme.club/vkredirect
  bucketName: linkme-store-dev
